### ISSUE TITLE
Add the ClearScript.v8 DLL's to the nuget lib folder

### ISSUE THREAD

**Issue by yesman85** [Taritsyn/JavaScriptEngineSwitcher#14]
We were investigating why our repo was getting slow and it turns out it wasn't liking the v8-ia32.dll and v8-x64.dll files.

They are included in the project and have to be checked in otherwise they won't be copied to the bin folder.

Is there a reason they are included in the project instead of just put in the lib folder in the nuget package? If they are in the lib folder the DI server would just include them with releases and they wouldn't have to be checked in source control.

**Comment by Daniel15** [comment]
You don't have to check them into source control. Just use the "Add as
Link" feature in Visual Studio to include the DLL files in your project
directly from the NuGet package directory. It's unfortunate the
out-of-the-box config isn't ideal.

**Comment by yesman85** [comment]
But will this also work on like a deployment server?

**Comment by Daniel15** [comment]
Yeah, it should work, as long as the server pulls in NuGet packages and is
using MSBuild to build the project

**Comment by Taritsyn** [comment]
Hello, Roger!

I store native assemblies in the `content` directory of NuGet package in order to ensure compatibility with [WebMatrix](https://www.microsoft.com/web/webmatrix/). If you are working in Visual Studio, then you should not have any problems when working with source control, because these problems have been solved in the [JavaScriptEngineSwitcher.V8 version 1.4.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v1.4.0). By using the [`JavaScriptEngineSwitcher.V8.props`](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/734974e84f7082649765ef56b7fdb1281e08040f/NuGet/JavaScriptEngineSwitcher.V8/build/JavaScriptEngineSwitcher.V8.props) file the native assemblies added to the project as a links.Then by using the [`Install.ps1`](https://github.com/Taritsyn/JavaScriptEngineSwitcher/blob/734974e84f7082649765ef56b7fdb1281e08040f/NuGet/JavaScriptEngineSwitcher.V8/tools/Install.ps1) file from project are removed the native assemblies, which has been added as content items. Therefore, no problems with source control should not arise.

**Comment by yesman85** [comment]
I guess I opened this issue a little too early then! I just upgraded from 1.3 to 1.4.1 and it seems to work!

Thanks!

**Comment by github-prometheus** [comment]
I am having the similar issue. I am using the version 2.1.0 and the clearscript native dlls gets copied to the output directory but with the folder structure and I get the following error :
```
Cannot load V8 interface assembly. Load failure information for v8-x64.dll:
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\a2329ee5\aedb85b8\assembly\dl3\87aa13f6\00e8b900_1335d201\v8-x64.dll: The specified module could not be found
D:\repo\MyWebProject\v8-x64.dll: The specified module could not be found
D:\repo\MyWebProject\bin\v8-x64.dll: The specified module could not be found
   at JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings)
   at JavaScriptEngineSwitcher.V8.V8JsEngineFactory.CreateEngine()
   at JavaScriptEngineSwitcher.Core.JsEngineSwitcher.CreateEngine(String name)
   at BundleTransformer.Less.Internal.LessCompiler..ctor(Func`1 createJsEngineInstance, VirtualFileManager virtualFileManager, CompilationOptions options)
   at BundleTransformer.Less.Translators.LessTranslator.Translate(IList`1 assets)
   at BundleTransformer.Core.Transformers.TransformerBase.Translate(IList`1 assets, Boolean isDebugMode)
   at BundleTransformer.Core.Transformers.TransformerBase.Transform(IList`1 assets, BundleContext bundleContext, BundleResponse bundleResponse, VirtualPathProvider virtualPathProvider, Boolean isDebugMode)
```

It will work correctly if I copy the dlls to the bin folder using the post build event. 

Am I missing something here or is it as designed ?

Thanks,
Prometheus

**Comment by yesman85** [comment]
Install the 32 bit and 64 bit Microsoft DLL packages

**Comment by Taritsyn** [comment]
> It will work correctly if I copy the dlls to the bin folder using the post build event.

@github-prometheus You don't need to copy anything into the `bin` directory. During installation of the [JavaScriptEngineSwitcher.V8.Native.win-x86](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x86) and [JavaScriptEngineSwitcher.V8.Native.win-x64](https://www.nuget.org/packages/JavaScriptEngineSwitcher.V8.Native.win-x64)  packages in project are added all necessary MSBuild-scripts.
