### ISSUE TITLE
Issue on deployment

### ISSUE THREAD

**Issue by PaulInglis** [Taritsyn/JavaScriptEngineSwitcher#15]
Hi, I have an issue when I'm deploying the files.  I always get an "access denied" when trying to delete the ClearScript.V8/ClearScriptV8-32.dll file.  What does this file do and why is IIS still holding on to it when I'm trying to deploy files?

**Comment by Taritsyn** [comment]
Hello, Paul!

`ClearScriptV8-32.dll` file contains a native .NET wrapper around the 32-bit version of V8 JS engine (`v8-ia32.dll` file). In general, without this file the JavaScriptEngineSwitcher.V8 will not work.

To remove this file you need to stop website.

**Comment by momadthenomad** [comment]
@Taritsyn am I correct in assuming that the latest 2.X release of JavaScriptEngineSwitcher.V8 will not have the same file locking issue?

**Comment by Taritsyn** [comment]
Hello, Mohamed!

This problem is more general and typical not only for the JavaScript Engine Switcher. Since a days of Classic ASP there is a simple rule: “Do not update the native assemblies, when web application is running.”. In .NET Framework for updating of native assemblies always require an restart of IIS or application pool.

.NET Core doesn't have this problem, because it uses a different approach to working with the native assemblies (mechanism based on the `runtimes` directories and [RIDs](https://docs.microsoft.com/en-us/dotnet/core/rid-catalog)).
