### ISSUE TITLE
Issue deploying application (v8-ia32.dll)

### ISSUE THREAD

**Issue by keymaker19** [Taritsyn/JavaScriptEngineSwitcher#31]
Hello I'm having the following issue with the  JS Engine Switcher V8 2.4.2 : 
Locally everything works OK,  I have installed the latest microsoft visual c++ redistributable package.
When I deploy my asp.net mvc application in the hosting I'm having this error when I run it

Cannot load V8 interface assembly. Load failure information for v8-ia32.dll:
C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\bfadc018\8b46cc3b\assembly\dl3\90b800db\753db974_23e1d201\v8-ia32.dll: The specified module could not be found
D:\InetPub\vhosts\site\httpdocs\v8-ia32.dll: The specified module could not be found
D:\InetPub\vhosts\site\httpdocs\bin\v8-ia32.dll: The specified module could not be found]
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessRequest(HttpContextBase context) +564
   BundleTransformer.Core.HttpHandlers.AssetHandlerBase.ProcessRequest(HttpContext context) +40
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +188
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +69

I have read online that is because of the microsoft redistributable package is not installed in the hosting, but I can't do that. I read on this issue in https://github.com/Taritsyn/JavaScriptEngineSwitcher/issues/11
that Taritsyn said: "What's stopping you to add the msvcp110.dll and msvcr110.dll assemblies in your application package?"
That's what I want to do,  deploy the JavaScriptEngineSwitcher c++ dependency with my application together and to avoid the requirement of have the redistributable installed on the server. Install the redistributable package in the hosting is not an option because is not a private virtual server.
Thank you

**Comment by Taritsyn** [comment]
Hello,  Keymaker19!

> That's what I want to do, deploy the JavaScriptEngineSwitcher c++ dependency with my application together and to avoid the requirement of have the redistributable installed on the server.

I will not do it, because you can yourself add a 32- and 64-bit versions of `msvcp140.dll` assembly (contains in the [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=52685)) to the `x86` and `x64` subdirectories of `bin` directory.

Also I recommend you to read the [“JS Engine Switcher: V8”](https://github.com/Taritsyn/JavaScriptEngineSwitcher/wiki/JS-Engine-Switcher:-V8) section of documentation and the “V8” section of [“Misconceptions about the JavaScript Engine Switcher version 2.X”](https://github.com/reactjs/React.NET/issues/409) post.
