### ISSUE TITLE
Removing package JavaScriptEngineSwitcher.ChakraCore.Native.win-x64 v2.4.6 doesn't remove Error task in csproj file for checking existence of package props

### ISSUE THREAD

**Issue by bbsdddougla** [Taritsyn/JavaScriptEngineSwitcher#46]
After removing the previous package, installing the new one, and building, I get the following error in projects where the package was removed:
```
C:\path\to\project\project.csproj(2001,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.2.4.6\build\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.props.
```

Removing the following task from the .csproj fixed the problem:
```xml
<Error Condition="!Exists('..\packages\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.2.4.6\build\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.2.4.6\build\JavaScriptEngineSwitcher.ChakraCore.Native.win-x64.props'))" />
```

**Comment by Taritsyn** [comment]
Hello!

Before publishing of NuGet packages, I always test them on different types of .NET and ASP.NET applications. When testing, I did not find any problems.

This problem can have two causes:

1.  After updating of package, you have overwritten the `.csproj` file by earlier version.
2. During updating of package a failure occurred, that caused by locking the `ChakraCore.dll` assemby by the IIS Worker Process (`w3wp.exe`) . Since a days of Classic ASP there is a simple rule: “Do not update the native assemblies, when web application is running.”.

If you don't believe me, then you can check on another project.

**Comment by bbsdddougla** [comment]
Ok, I'll close this.
