### ISSUE TITLE
V8.Net?

### ISSUE THREAD

**Issue by rjamesnw** [Taritsyn/JavaScriptEngineSwitcher#69]
[V8.Net](https://github.com/rjamesnw/v8dotnet) now supports Net Standard, and will be _part_ of the back-end server for the [FlowScript ](https://github.com/rjamesnw/FlowScript) VPL system (coming soon). It has an extremely fast interface between the CLR and V8, but in a way that is cross-platform.

**Comment by Taritsyn** [comment]
Hello, James!

Thanks for information! As soon as I have free time, I'll research your library.

The main thing that your library does not repeat the fate of [VroomJs](http://github.com/pauldotknopf/vroomjs-core).

**Comment by rjamesnw** [comment]
I assume you mean abandoned? Hopefully not. ;) V8.Net has been around since 2013. ;)

**Comment by Taritsyn** [comment]
NuGet package appeared only today.

**Comment by rjamesnw** [comment]
I meant for .Net 3.5 and 4 since 2013. I never got around to supporting NuGet.

**Comment by jtreher** [comment]
@rjamesnw Since [Edge is switching to V8](https://github.com/Microsoft/ChakraCore/issues/5865), it seems practical to support V8 for .net core running on linux as ChakraCore is in wind down mode. If @rjamesnw project has been maintained for several years, it seems like a good option to move forward.

**Comment by Taritsyn** [comment]
@jtreher Have you tried running the V8.Net library under Linux or Mac?

**Comment by rjamesnw** [comment]
The project currently uses a Visual Studio project to compile the wrapper C++ against the V8 source. I added in support to search and load the correct libraries on Windows or Linux, but as I’m not a Linux guy I never yet compiled any Linux binaries. Others have very easily ported the project to mono in the past (before .Net Core; https://www.nuget.org/packages/V8.Net.Mono/ [outdated now]) without issue. If someone wants to help get the C++ wrapper compiling Linux libraries again it would be welcome.

**Comment by tombatron** [comment]
I'm not sure that this is the correct venue for the extended discussion, but I was tinkering around with the V8.Net source under WSL. 

I was able to get the V8 source compiled with no issues, though I had major issues getting the actual V8.Net proxy code compiled... Probably because I'm hopelessly out of my depth. 

I guess the point of my reply is that it appears that the WSL environment would be sufficient for building and testing a Linux binary.

**Comment by rjamesnw** [comment]
Thanks for the heads up. I’ve been investigating WSL and may try to work out a solution using that at some point.

**Comment by tombatron** [comment]
For anyone else following along at home:

I got a little farther in my attempts at getting V8.Net's proxy compiled under Linux. I posted the issue that stopped me in my tracks here: https://github.com/rjamesnw/v8dotnet/issues/28

Another thing that I encountered when trying to use V8.Net under Windows to render a React component is documented here: https://github.com/rjamesnw/v8dotnet/issues/27

**Comment by Taritsyn** [comment]
I'm closing this issue because the [Microsoft ClearScript.V8 7.0](https://github.com/microsoft/ClearScript/releases/tag/7.0.0) now supports Linux and macOS. In addition, [JavaScript Engine Switcher 3.9.0](https://github.com/Taritsyn/JavaScriptEngineSwitcher/releases/tag/v3.9.0) now uses the official NuGet packages of this library.
